[C;R0;X4]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH]!@[CH][CH2]	10_alkyl_chain	proceed_with_caution
c([OH])c([OH])c([OH])	2_3_4_trihydroxyphenyl	
c([OH])cc([OH])c([OH])	2_4_5_trihydroxyphenyl	
[C;R0;X4]!@[CH2]!@[CH2]!@[CH2]!@[CH2]!@[CH2]!@[C;R0;X4]	6_alkyl_chain	proceed_with_caution
O=CC([$(C(F)(F)F),$(C#N),$(Cl)])=C	ab_ketones	
[$(O([CX4,c])!@[CH,CH2]!@O[CX4,c])]	acetal	proceed_with_caution
C[OD2H0][CD2H2][OD2H0]C#C	acetal_alkyne	showstopper
[CD2H1](=[CX3])[OD2H0][CX4][OD2H0]	acetal_alkene	red_flag
[S,C](=[O,S])[Cl,Br,I,F]	acid_halide	showstopper
[$(C#N),$([C,N,S]=O)][CH2,CH][$([C,N,S]=O),$(C#N)]	acidic_CH	unsure
[$(C-[Cl,Br,I]),$(O=C-[Cl,Br,I,F]),$(O=C([CH,CH2][Cl,Br,I,F])[O,C]),$(C~O~[Cl,Br,I,F][CH,CH2]),$(n1c([Cl,Br,I,F])nccc1);!$(C=C-[Cl,Br,I]);!$(ClC-[Cl,Br,I,F])]	active_halo	ok
N([H,C;X4])([H,C;X4])-[C;R0;X4]-N[C;X4]([H,C;X4])([H,C;X4])	acyclic_aminal	ok
N#C[C;R0;X4]O[!$(O=[C,S])]	acyclic_cyanohydrin	unsure
[C;R0](=[C;R0])-[S,O,N;R0][!$(O=[C,S])]	acyclic_enol_1	unsure
[C;R0](=[C;R0])-[OH]	acyclic_enol_2	unsure
[O-]-[C;R0]=[C;R0]	acyclic_enol_3	unsure
[NR0]([CR0][$([NR0]#C);!$([NR0]=C)])	acyclic_NCN	showstopper
N(S)=[S,N,O]	acyclic_NS	showstopper
[N;R0](~N)~O	acyclic_nitroamino	unsure
N#CC(=O)[A]	acyl_cyanide	showstopper
NNC=O	acyl_hydrazine	red_flag
C[NR0][NR0]C(=O)A=C	acylhydrazide	showstopper
C[N;R0][N;R0]C(=O)[A]	acylhydrazide	red_flag
[CX3]=[CX3][OD1H1]	allenic_alcohol	showstopper
C(#C[CD2H2][OD1H1])[CD1H3]	allenic_alcohol	red_flag
[C;H1](=O)[#6]	aldehyde	showstopper
[CD2;R0][CD2;R0][CD2;R0][CD2;R0][CD2;R0][CD2;R0][CD2;R0]	aliphatic_methylene_7_or_more	unsure
[N;R0]=[N;R0]=[C;R0]	alkyl_diazo	unsure
[Br,Cl,F,I][CX4H2]	alkyl_halide	showstopper
P(O[C,c])(O[C,c])(O[C,c])=O	alkyl_phosphate	showstopper
[S,P](=O)(=O)OC	alkyl_PS_esters	unsure
S=[CD3H0]1[CD3H0](=[CD2H1]1)[ND3H0]([CD1H3])[CD1H3]	alkyl_aniline	showstopper
[N;D3;H0]	alkyl_aniline	ok
[CD1H3][NX3]ccc[o,s,n]	alkyl_aniline	red_flag
C#[CH]	terminal_alkyne	proceed_with_caution
C#C[F,Cl,Br,I,Si]	alkyne_halogenated_or_Si	showstopper
[Br,Cl,F,I][CH]C=C	allyl_halide	showstopper
[Br,Cl,F,I]C=C=C	allyl_halide	showstopper
[OH][CX4][$([NH2]),$([NH][CX4]),$(N([CX4])[CX4])]	alpha_amino_hydroxyl	ok_doublecheck
[ND3]([CX4,c,H])([CX4,c,H])[CX4][$([CH]),$(C([CX4,c]))]=O	alpha_amino_ket_or_ald	showstopper
cCC(=O)[OH]	alpha_aryl_ca	red_flag
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=C-C#N	alpha_beta_CN	unsure
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=C-[$([CH]),$(C([CX4,c]))]=O	alpha_beta_ket_or_ald	showstopper
C=CC(=O)[OH]	alpha_beta_unsat_ca	showstopper
N#C-C(=O)[OH]	alpha_cyano_ca	showstopper_doublecheck
[OH][CX4][Cl,Br,I]	alpha_halo_hydroxyl	red_flag
[F,Cl,Br,I]CC=[O,C]	alpha_halocarbonyl_or_alpha_haloalkene	showstopper
[OH][CX4][$([CH]),$(C([CX4,c]))]=O	alpha_hydroxy_ket_or_ald	showstopper_doublecheck
[#6]C(=O)C(=O)[OH]	alpha_keto_ca	showstopper_doublecheck
N(~O)(~O)-C-C(=O)[OH]	alpha_nitro_ca	showstopper_doublecheck
C([Cl,Br,I])([Cl,Br,I])([Cl,Br,I])C(=O)[OH]	alpha_trihalo_ca	showstopper_doublecheck
N1C([Br,Cl,F,I])CC=C1	alpha_halo_amine_1	showstopper
NC[Br,Cl,F,I]	alpha_halo_amine_2	red_flag
N[$([CX3]=[CX3])][Br,Cl,F,I]	alpha_halo_amine_3	red_flag
[Cl,Br,I][$([CX4][CH]=O),$([CX4]C(=O)[CX4,c])]	alpha_halo_ket_or_ald	showstopper
O=C([c,CX4])[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]	amide	ok
O=C([$([CX2](#C)),$([CX3]=[CX3])])[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]	amide_alkyl_or_alkene	showstopper
NCN	aminal	ok
[CX4]N[CH2]O[CX4]	hemiaminal_ether	showstopper
[$([NH2][CX4]),$([N;D4]),$([$([NH]([CX4])[CX4]);!$([NH]([CX4])[CX4][O,N]);!$([NH]([CX4])[CX4][O,N])]),$([ND3]([CX4])([CX4])[CX4])]	amine_any	ok
[NH2][$(C=C),$(CC#C)]	amine_alkene/alkyne	showstopper
[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4]);!$(NC=O)][CX4]C(=O)[OH]	amino_acid	ok
O=C(NC)C1=CCC(C)=N1	amino_acid_specific_issues	proceed_with_caution
[CD1H2]=[CD3H0]([CD3H0]([OD1H1])=[OX1-0])[ND2H0]=[CD2H1][CD1H3]	amino_acid_specific_issues	red_flag
[CD2H1]=1[CD2H2][CD3H1]([CD3H0]([OD2H0][CD3H0][CD2H1]=1)=[OX1-0])[ND2H0]	amino_acid_specific_issues	showstopper
C(=O)OC(=O)	anhydride	ok #?
O(C(=O)[#6])(C(=O)[#6])	anhydride_specifically_problematic_with_alkyl red_flag #?	
[NX3][$(C=C),$(cc)]	aniline	ok
c12cc1ccc2[NX3]	5_3_aniline	showstopper
c21cccc1c2[NX3]	3_5_aniline	showstopper
[NX3][cX3]1[cX3H][cX3H][cX3H][cX3H][cX3H]1	phenylaniline	proceed_with_caution
c-[ND3]([#6])[#6]	aniline_disub	ok
c1c(cccc1)S(=O)(=O)N2[C;N]=CC=C2	arene_sulfonyl_pyrrole-pyrazole	proceed_with_caution
c1c(cccc1)S(=O)(=O)N2C=NC=C2	arene_sulfonyl_imidazole	showstopper
cN=[N+]=[N-]	aromatic_azide	proceed_with_caution
[Cl,Br,I,F]N=[N+]=[N-]	halo_azide	proceed_with_caution
cB([OH])[OH]	aryl_boronate	ok
Fcaa[F,Cl,Br,I,$([C,N,S]=O)]	aryl_fluoride	ok #?
[N;C]1([c;n]ccc1)[F,Cl,Br,I]	aryl_halide_specific	showstopper
[N-][N+]#N	azide_1	proceed_with_caution
N=[N+]=[N-]	azide_2	proceed_with_caution
[N;R0;D2]~[N;R0]~[N;R0;D1]	azide_3	proceed_with_caution
[Cl,Br,F,I]N=[N+]=[N-]	azide_halide	showstopper
C1C[N;!H0]1	aziridine	showstopper
[N;D2]([C,c;!$(C=[O,S,N])])=[N;D2]-[C,c;!$(C=[O,S,N])]	azo	showstopper_doublecheck
[N;R0]=[N;R0]CC=O	azoalkanals	showstopper_doublecheck
[a,A][N;R0]=[N;R0]C#N	azocyanamides	showstopper
[C,N]1=[C,N][CD3H0]([C,N]=[C,N]1)=[CD1H2]	azo_pyrrazole	showstopper
[CD1H2]=[CD3H0]1[CD2H2][ND2H0]=[ND2H0][CD2H2]1	azo_pyrrazole	showstopper
[CD1H3][CD3H0]=1[ND2H0]=[ND2H0][CD2H2][CD2H1]=1	azo_pyrrazole	proceed_with_caution
[NH]=C([NH2])c	benzamidine	red_flag #?
c1ccccc1CO[c,C]	benzyl_ether	proceed_with_caution
c1ccccc1[CX2][O,OX1][c,C]	benzyl_ether_alkyl	showstopper
[CD2H1][OD2H0][CD3H0][cH0]:1:[cH1]:[cH1]:[cH1]:[cH1]:[cH1]:1	benzyl_ether_alkyl	showstopper
[C;H2]([F,Br,Cl,I])c	Benzyl_halide	red_flag #?
cC[N+]	benzylic_quat_nitro unsure	
c1ccccc1COC(=O)[N,n]	benzyloxycarbonyl_CBZ	showstopper
[OH][CX4][CX4][$([NH2]),$([NH][CX4]),$(N([CX4])[CX4])]	beta_amino_hydroxyl	unsure	
C[N+](C)(C)CCC=O	Beta_ammonium_carbonyl	unsure	
[a,A]C(=O)CN=N	beta_azo_carbonyl	showstopper
[N+,n+]CCC(=O)	beta_carbonyl_quat_nitrogen1 unsure
C1[N+,n+]C(=O)C1	beta_carbonyl_quat_nitrogen2	showstopper
C1[N,n;R1;D3]C(C1)=O	beta_carbonyl_quat_nitrogen3	showstopper
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=C[CX4]C(=O)[OH]	beta_gamma_unsat_ca	unsure	
[CX4]([Cl,Br,I])[CX4]C(=O)[OH]	beta_halo_ca	unsure
[F,Cl,Br,I]CCC(=O)	beta_halo_carbonyl	showstopper
[OH][CX4][CX4][Cl,Br,I]	beta_halo_hydroxyl	unsure
[F,Cl,Br,I]CCN	beta_haloamine	ok
[F,Cl,Br,I]CCC=O	beta_halocarbonyl	unsure
[CX4]([OH])[CX4]C(=O)[OH]	beta_hydroxy_ca 	unsure
[#6]C(=O)[CX4]C(=O)[OH]	beta_keto_ca	unsure
[#6]C(=O)[CX4]C(=O)O[$([#6]);!$(C=[O,S,N])]	beta_keto_ester		unsure
[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]C(=O)O[$([#6]);!$(C=[O,S,N])]	carbamate	unsure	
[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]C(=O)[O-]	carbamic_acid	unsure
[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]C(=O)[O;!H0]	carbamic_acid_2	unsure	
O=CN=[N+]=[N-]	carbazide	unsure
N=C=N	carbodiimide	unsure
[CX4,c]OC(=O)O[CX4,c]	carbonate	unsure
O=C-N!@N	carbonyl_nn	unsure
[O,H1]CC(=O)[a,A]	carboxylic_acid_1	unsure
[O-]CC(=O)[a,A]	carboxylic_acid_2	unsure
[$([S;+]),$([P;+]),$([I;+]),$([C;+]),$([Cl;+]),$([O;+]),$([o;+])]	cation_C_Cl_l_P_or_S	unsure	
[Cl]C([C&R0])=N	chloramidines	unsure
[N;X3](Cl)	chloramine	unsure
ClC(=O)O[CX4,c]	chloroformate	unsure
Cl[Si;X4]	chlorosilane	unsure
[O;R1][C;R1][C;R1][O;R1][C;R1][C;R1][O;R1]	crownethers	unsure	
N[CH2]C#N	cyanamides	unsure
O=C=N	cyanate	unsure
[CX4,c]-C#N	cyanide	ok
[OH]c1cc([OH])cc2OC(C([OH])Cc21)c3cc([OH])c([OH])cc3	cyanidol_derivs	unsure
N#C[C;X4]([OH])([C,c,H])[C,c,H]	cyanohydrin	unsure
P(OCC)(OCC)(=O)C#N	cyanophosphonates	unsure	
O=C1NC(=O)CCC1	cyclohexamide_derivs	unsure
[C;R1][C;R1][C;R1]	cyclopropal	ok
c1ccccc1CC2[NH]C(=O)C3[CH]2CCC(O)C3	cyctochalasin_derivs	showstopper
O=C1NCC2CCCCC21	cytochalaisn_dervs_2	showstopper
P(=O)([OH])OP(=O)[OH]	di_tri_phosphates	showstopper
[$([#6]=[N+]=[N-]),$([#6-]-[N+]#[N])]	diazo	showstopper_doublecheck
[NX3](Cl)Cl	dichloramine	showstopper
N[CX4]C(=O)N[CX4]C(=O)	dioxane_5MR	red_flag
C1OCCCOC1	dioxane_6MR	red_flag
C1OCCO1	dioxane_6MR	red_flag
[S;D2]-[S;D2]	disulfide	showstopper
[$([S;D2]([CX4,c])!@[CH,CH2]!@[S;D2][CX4,c])]	dithioacetal	showstopper
[$(N#CSc1sc(nc1)N),$([S,Se]1C(N)C(=O)[#6][#6]1)]	electrophiles_for_cyc	showstopper
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=[$([CX3][$([NH2]),$([NH][CX4]),$([N;R0]([CX4])[CX4])]);!$(CC=[O,S,N]);!$(C[O,S])]	enamine	red_flag
[CH2]=[CH]-[N,O,S]	end_vinyl	showstopper
[$([CX3]C(=O)[CX4,c]);!$(CC=[S,N]);!$(C[O,S,N])]=[$([CX3]C(=O)[CX4,c]);!$(CC=[S,N]);!$(C[N,S])]	enedione	showstopper
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=[$([CX3][OH]);!$(CC=[O,S,N]);!$(C[N,S])]	enol	red_flag
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=[$([CX3]O[CX4]);!$(CC=[O,S,N]);!$(C[N,S])]	enol_ether	showstopper
C1[O,S,N]C1	epoxides_thioepoxides_aziridines	showstopper
[$([#6]);!$(C=[O,S,N])]C(=O)O[$([#6]);!$(C=[O,S,N])]	ester	ok
[$(O([$([CX4,c]);!$(C[O,N,S])])[$([CX4,c]);!$(C[O,N,S])]);!$(O1[CX4][CX4]1)]	ether	ok
NC(=O)OCC3c1ccccc1c2c3cccc2	fmoc	red_flag
C1(=O)OCC1	four_mem_lactone	red_flag
[nH]c([nH2])[nH2]	guanidine	red_flag
NC(N)=N	guanidine	red_flag
[Cl,Br,I]C=C	halo_alkene	showstopper
FC=C	halo_alkene	proceed_with_caution
[F,Cl,Br,I][CH2][OH0;X2]	halo_methylether	red_flag
[F,Cl,Br,I][CH2][SH0;X2]	halo_methylthioether	red_flag
P[Cl,Br,F,I]	halo_phosphane	showstopper
[F,Cl,Br,I]N	haloamine	showstopper
[OH][CH,CH2]O[CX4,c]	hemiacetal	showstopper
O([#6])-C([#6])([#6])-[OH]	hemiketal	showstopper
[O,N,S][CH2]N1C(=O)CCC1(=O)	het_imides	red_flag
n1nn(OC(=O))c2ccccc12	HOBT_esters	showstopper
[$([NH;R0]([C;!$(C=[O,S,N])]))][$([NH;R0][C;!$(C=[O,S,N])])]	hydrazine	proceed_with_caution
[N;R0][N;R0]=C	hydrazone	showstopper
N=NC(=S)N	hydrazothiourea	red_flag #doublecheck?_Need_to_be_more_specific?
O=CN[OH,O-]	hydroxamate	red_flag #doublecheck?_Need_to_be_more_specific?
ON[C;!$(C[O,S,N])]	hydroxamic_acid	red_flag #doublecheck?_Need_to_be_more_specific?
[OH][$([NX3]([C;!$(C=[O,S,N])])[C;!$(C=[O,S,N])]),$([NH][CX4])]	hydroxy_amine	showstopper
C(=O)Onnn	hydroxybenzoyltriazole	ok #?
C=NC=O	imide	ok
[Cl,Br,F,I]C=N	imidoyl_halide	showstopper
[$([C;R0]=[N;R0]);!$(C(~[N,O,S])(~[N,O,S]));!$([C;R0]=[N;R0]~[N,O,n])]	imine	red_flag
[IX2]=O	iodoso	showstopper
O=I=O	iodoxy	showstopper
[#6]N=C=O	isocyanate	showstopper
C#N-[#6]	isocyanide	showstopper
[N+]#[C-]	isonitrile	showstopper
[#6]N=C=S	isothiocyanate	showstopper
O([CX4,c])-C([CX4,c])([CX4,c])-O([CX4,c])	ketal	showstopper
C=C=O	ketene	red_flag	
[CX4,c]C(=O)[CX4,c]	ketone unsure	
O=CON1C(=O)CCC1=O	labile_ester_1	showstopper
O=COn1cncc1	labile_ester_2	showstopper
Fc1c(OC=O)c(F)c(F)c(F)c1F	labile_ester_3	showstopper
[$([C;R1]);!$(C(N)N)](=O)@[$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]	lactam	ok
[CD2H2R1][CX3R1](=[C,O])[C,N;R1]	lactam_1	proceed_with_caution
[$([C;R1]);!$(C(O)N);!$(C(O)O)](=O)@[$(O);!$(O(C=O))]	lactone	ok
[CD2R1][CX3R1](=[C,O])[O;R1]	lactone_1	proceed_with_caution
P(=S)(S)S	lawesson_s_reagent	showstopper
[C;R0;X4]!@[CX4]!@[CX4]!@[CX4]!@[CX4]!@[CX4]!@[C;R0;X4]	long_chain	proceed_with_caution
[R8,R9,R10,R11,R12,R13,R14]	macrocycle	ok
C1(=O)CC(=O)C1	malonic_acid_cBu	showstopper
C(=O)CC(=O)[OH,C,N,S]	malonic_acid	proceed_with_caution
[S,s;D2]C[S,s;D2]	masked_aldehyde_q	unsure
COCCOC	mem	red_flag
[Be,B,Al,Ti,Cr,Mn,Fe,Co,Ni,Cu,Pd,Ag,Sn,Pt,Au,Hg,Pb,Bi,As,Sb,Gd,Te,Se,se]	metals_and_other_elem	proceed_with_caution
[CX4,c]C(=O)[CX4,c][CX4,c]	methylketone	red_flag
[$(N#C-C=[CH][C,c]),$([CH](=[C;R0]-[CH]=O)),$([CH](=[C,R]-C(=O)-C));!$([CH]1=CC(=O)C=CC1=*);!$([CH]1=CC(=O)C(=[N,O])C=C1);!$([CH](=C-C=O)-C=O)]	michaels_acceptor	showstopper
[$(N#C-C#C[C,c]),$(C#C-[CH]=O),$(C(#C-C(=O)-[C,c]))]	michaels_acceptor_enyne	showstopper
O1CCCCC1C2CCCO2	monensin_deriv	red_flag
[Cl,Br,I]CC[S,N]	mustards	showstopper
OC[N+X4]C	n_methoyl	showstopper
[$(N!@N),$([N;R0]=[N;R0])]	N_N	red_flag
[!$([C,c]-N(=O)~O);$([!O]~[N;R0]=O)]	n_oxide	showstopper
[S,P][Br,F,I,Cl]	n_p_s_halides	showstopper
[$(N!@S),$(N~C(~S)-N)]	N_S	ok
*-C#N	nitrile	ok
*-[$([N;X3]=O),$([N+;X3]=O)]~[O,O-]	nitro	red_flag
[N+]([O-])(=C)-*	nitrone	red_flag
[$([A,a]);!$([O,o])][N&D2](=O)	nitroso	showstopper
C=NN[$(C);!$(C=O)]	nonacylhydrazone	showstopper
[S,N]CC[Br,F,I,Cl]	ns_beta_halothyl	ok
[#5,#13,#14,#31,#32,#33,#50,#51,#52,#84,#83,#82,#81,#3,#4,#11,#12,#19#20,#37,#38,#55,#56]C	organometallic	proceed_with_caution
CC(=O)C(=O)C	oxalyl_omega	showstopper
OC(=O)C(=O)O	oxalyl_rlewis	showstopper
C1NO1	oxaziridine	showstopper
C=[N;R0]-[OH]	oxime	showstopper
[O-][N+](=O)c1ccc(OC=O)cc1	paranitrophenyl_ester_1	showstopper
ON(=O)c1ccc(OC=O)cc1	paranitrophenyl_ester_2	showstopper
[O-][N+](=O)c1ccc(OC=O)cc1	paranitrophenyl_ester_3	showstopper
C(=O)Oc1ccc([$([N;X2]=O),$([N+;X2]=O)][O,O-])cc1	paranitrophenyl_esters	showstopper
Fc1c(F)c(F)c(OC=O)c(F)c1F	pentafluorophenyl_esters	showstopper
C([F,Cl,Br,I])([F,Cl,Br,I])([F,Cl,Br,I])C(=O)[CX4,c]	perhalo_ketone	showstopper
O~O	peroxide	showstopper
c:1([O]):c:c:c:c:c:1	phenol	proceed_with_caution
O=P(~O)(~O)(~O)	phosphate	showstopper
P(=O)(O[H,C])O[H,C]	phosphinate	showstopper
[PX4](=O)(C)(C)~[OH,O-]	phosphinic_acid	showstopper
[PX4](=O)(N)(*)~[OH,O-]	phosphonamide	showstopper
[PX3](=O)(~O)~[OH]	phosphonic_acid	showstopper
[PX3](=O)(~O)~O-[#6]	phosphonic_ester	showstopper
[PX4](=O)(~O)(~O)C#N	phosphonylnitrile	showstopper
NP(=O)(N)N	phosphoramides	showstopper
C=[PD4]	phosphorane	showstopper
[PX5]	phosphorane	showstopper
[PX4](=O)(~O)(~[OH,O-])~[OH,O-]	phosphoric_acid	showstopper
[PX4](=O)(~O)(~O)~O-[#6]	phosphoric_ester	showstopper
[PX4](=O)(~O)(~O)~O-[A,a]	phosphoryl	showstopper
O=C2c1ccccc1C(=O)N2	phthalimides_pht	showstopper
C=CC=CC=CC=C	polyenes	showstopper
[CX4;H2][OH]	primary_alcohol	ok
[CX4][NH2]	primary_amine	ok
[C,O]=,#C[CX4][NH2]	primary_amine_reactive	showstopper
[F][CX4][NH2]	primary_amine_F	red_flag
C1(=O)OCC1	propiolactones	showstopper
P[S,N]	psn_bonds	red_flag
[n+]-C	pyridinium	ok
[S;D2][C;R0](C)(C)C	quarternary_S	ok
[c,C]1(~[O;D1])~*!-*~[c,C](~[O;D1])~*!-*~1	quinone	showstopper
O1CCCCC1OC2CCC3CCCCC3C2	saponin_deriv	red_flag
SC(N)(N)	scn2	red_flag
[CX4;H][OH]	secondary_alcohol	ok
[$([NH]([CX4])[CX4]);!$([NH]([CX4])[CX4][O,N]);!$([NH]([CX4])[CX4][O,N])]	secondary_amine	ok
C[C,N][C,N]C#C	secondary_amine_reactive	showstopper
[C;R0;X4][CH2][CH2][CH2][CH2][C;R0;X4]S	shtail	red_flag
[Si]~N	si_nbonds	red_flag
[Si]-O-*	silicate	red_flag
[C,c]-[S;D2]-[O,N]	son	red_flag
C12OCCC(O1)CC2	squalestatin_derv	showstopper
C14~*~*~*~*~C~1~*~*~C2~C3~*~*~*~C~3~*~*~C~2~4	steroid	red_flag
[CX4][S;D2][CX4][CX4]	sulfide	proceed_with_caution
[C,c]S(=O)N=[CH,CX3][C,c]	sulfinimine	red_flag
CS(=N)C	sulfinimine_oe	showstopper
[C,c]S(=N)(=O)[C,c]	sulfonimine	showstopper
CS(=O)SC	sulfinylthio	showstopper
S(=O)(=O)C#N	sulfonyl_cyanide	showstopper
[SD3](~O)(~O)[Cl,Br,F,I]	sulfonyl_halide_oe	ok
[C,c]S(=O)(=O)[N]C(=O)[NH][C,c]	sulfonyl_urea	ok
S(O[C,c,N,n])(~O)[C,c,N,n]	sulphate	ok
[#6][SD4](~O)(~O)N[Cl,Br,I]	sulfonamide_halogenated	showstopper
[C,c]OS(=O)(=O)[C,c]	sulfonate_ester	showstopper_doublecheck
[#6]([SD4](=O)(=O))[$([C;H1]=[C;H1]);$([C;H0]#[C;H0])]	sulfone	showstopper
[A]S(~O)(~O)[OH]	sulfonic_acid	showstopper
[#6]S(~O)(~O)O[#6]	sulfonic_ester	showstopper
[#6][SD4](~O)(~O)[Cl,Br,F,I]	sulfonyl_halide	showstopper
[#6][SD3](~O)[#6]	sulfoxide	showstopper
C(C)(C)(C)OC	t_butyl_ether	ok
[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]=[$([CX3]);!$(CC=[O,S,N]);!$(C[O,S,N])]	t_or_ald	ok
[CH2]=[CH]-[Br,Cl,I,F]	terminal_vinyl	showstopper
[CX4;H0][OH]	tertiary_alcohol	ok
[ND3]([CX4])([CX4])[CX4]	tertiary_amine	ok
[ND3]([CX4])([CX4])CF	tertiary_amine_F	red_flag
[ND3]([CX4])(C=C)C=C	tertiary_amine_unsat	showstopper
O1CCCCC1O	tetrahydropuran_thp	showstopper
O1CCCCC1O	tetrahydropuran_thp	showstopper
s1c(=N)nnc1[S,N]	thiadiazole	unsure
[C,c]C(=S)[Cl,Br]	thioacyl_Cl_Br	unsure
S=C([c,CX4])[$([NH2]),$([NH][c,CX4]),$(N([c,CX4])[c,CX4])]	thioamide	showstopper_doublecheck
[C,c]OC(=S)N([C,c])([C,c])	thiocarbamate_1	showstopper
[C,c]SC(=O)N([C,c])([C,c])	thiocarbamate_2	showstopper
[$([CX4,c][CH]=S),$([CX4,c]C(=S)[CX4,c])]	thiocarbonyl	ok
SC#N	thiocyanate	showstopper
[$([#6]);!$(C=[O,S,N])]C(=S)O[$([#6]);!$(C=[O,S,N])]	thioester	showstopper_doublecheck
[$([#16;D2]([$([CX4,c]);!$(C[O,N,S])])[$([CX4,c]);!$(C[O,N,S])]);!$([#16;D2]1[CX4][CX4]1);!$(s1aaaa1)]	thioester_2	showstopper_doublecheck
[SH]	thiol	ok
[$([S,s]~[S,s]~[C,c]=S),$([S,s]~[C,c](=S)~[S,s,N]),$([S;D2;R0]-S~O)]	thiolating_agent_q	showstopper
S=C-[#6,N,O]	thionyl	unsure
c[SH]	thiophenol	ok
NC(=S)N	thiourea	ok
N(C(=S)N)-,=C#,=C	thiourea_good_LG	showstopper
C(=O)N(C(=O))OC(=O)	triacyloximes	showstopper_doublecheck
NN=N	triazene	showstopper
[C,c]P([C,c])[C,c]	tricarbo_phosphine	showstopper
[$(O=C[CH](C=O)C=O),$(N#C[CH](-C=O)-C=O)]	tricarbonyls	unsure
OS(=O)(=O)C(F)(F)F	triflate	ok
[CH3][#14;X4]([CH3])[CH3]	trimethylsilyl_tms	showstopper
[D2R0]-[D2R0]-[D2R0]-[D2R0]-[D2R0]	unbranched_chain	ok
[Cl,Br,I,F][S,P,Si,N]	unstable_halide	showstopper_doublecheck
NC(=O)N	urea	ok
NC(=O)N=[CD3H0]	good_leaving_group_urea_1a	showstopper
[CD3H0]=CNC(=O)NC=[CD2H1]	good_leaving_group_urea_1b	showstopper
[CD2]=1[CD2][CD2]=[CD2][ND3]([CD2]=1)[CD3]([N])=[OX1-0]	good_leaving_group_urea_2	red_flag
[Cl,Br,I]C=CC=O	vinylous_acid_halogens	showstopper_doublecheck
